version: 1.2
workflows:
  - name: countNsSlow_matuska
    subclass: WDL
    primaryDescriptorPath: /slow/workflow.wdl
  - name: countNsFast_matuska
    subclass: WDL
    primaryDescriptorPath: /fast/workflow.wdl
